/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BangumiDetail: typeof import('./../components/page/template/BangumiDetail.vue')['default']
    Builtin: typeof import('./../components/site/captcha/builtin.vue')['default']
    Cloudflare: typeof import('./../components/site/captcha/cloudflare.vue')['default']
    Model: typeof import('./../components/site/Model.vue')['default']
    Turnstile: typeof import('./../components/site/captcha/turnstile.vue')['default']
  }
}
