/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Captcha: typeof import('../components/site/Captcha/Captcha.vuea/Captcha.vue')['default']
    Card: typeof import('./../components/comment/vue/Card.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    Form: typeof import('./../components/comment/vue/Form.vue')['default']
    List: typeof import('./../components/comment/vue/List.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
  }
}
